[package]
name = "alc"
version = "0.9.9"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
ordered-float = "5.0.0"
tower-lsp = "0.20"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }

[[bin]]
name = "alc"
path = "src/main.rs"

[[bin]]
name = "alum-lsp"
path = "src/lsp/alum-lsp.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = "symbols"
